name: "mttsFly"
main: me.mttprvst13.fly
version: "1.5.2 BETA"
description: "A plugin that adds fly mode."
author: mttprvst13
commands:
   fly:
      description: Toggles fly mode.
      usage: /<command> [playername] [on|off]

permissions:
    mfly.*:
        description: Gives access to all Mtt Fly commands.
        children:
            fly.canfly: true
            fly.sayhey: true
            fly.willfly: true
    mfly.canfly:
        description: Gives access to the fly command
        default: op
    mfly.willfly:
        description: Sets fly mode to true when the user logs in.
        default: op